name: Capture Health
description: Free to record your Blood Pressure and Pulse  by take photo!
full_description: 'Free to record your Blood Pressure and Pulse  by take photo!<br>
<br>With a lot of features:
<br>- Record your Blood Pressure and Pulse  by take photo
<br>- Early prevention of cardiovascular diseases
<br>- Say goodbye to complicated handwritten records
<br>- Export data to local anytime'
android: https://download1587.mediafire.com/2cqp1ks7ifqgn7dAMIQZoBbfrU8CXs0ZFY4jKjGQj6vO4zwRp4OalVu3uxoAItfWZNAOdpNzv-gC0MqkoRMyvBfNOjpzXu9tK8B_kY3NFcFdahr6LHnAw6v19cS94b1sf11uQ4x6eXnOEAmTWKRQn0i4an--kj8DXwAP508c2WP9gQg/krm2xbapb1payde/app-release.apk
web: https://download1587.mediafire.com/2cqp1ks7ifqgn7dAMIQZoBbfrU8CXs0ZFY4jKjGQj6vO4zwRp4OalVu3uxoAItfWZNAOdpNzv-gC0MqkoRMyvBfNOjpzXu9tK8B_kY3NFcFdahr6LHnAw6v19cS94b1sf11uQ4x6eXnOEAmTWKRQn0i4an--kj8DXwAP508c2WP9gQg/krm2xbapb1payde/app-release.apk
screenshots:
  - IMG_20240106_093454.jpg
  - IMG_20240106_093547.jpg
  - IMG_20240106_100518.jpg
producthunt: https://www.producthunt.com/posts/capturehealth
companies:
  - url: https://www.producthunt.com/posts/capturehealth
    image: producthunt.png
