name: Capture Health
description: Free to record your Blood Pressure and Pulse  by take photo!
full_description: 'Free to record your Blood Pressure and Pulse  by take photo!<br>
<br>With a lot of features:
<br>- Record your Blood Pressure and Pulse  by take photo
<br>- Early prevention of cardiovascular diseases
<br>- Say goodbye to complicated handwritten records
<br>- Export data to local anytime'
android: https://download948.mediafire.com/a7fznh5iocmg84MYsaXAM39szio_MslHxhkRrXMHPFA8IYWpvyj8s4kTuIqTYamOxGRG0dR817I9NZRgld-hp6HzIPLcl0MuPtv4AVy8O3mcHTkzvJ-X-Dh4FqOlv7S9b0VkNK_w2GOG4jQ5iqBtoZ34umWvhUWiJXRS9SfB-vVE_zI/33muervatr8acwq/app-release.apk
web: https://download948.mediafire.com/a7fznh5iocmg84MYsaXAM39szio_MslHxhkRrXMHPFA8IYWpvyj8s4kTuIqTYamOxGRG0dR817I9NZRgld-hp6HzIPLcl0MuPtv4AVy8O3mcHTkzvJ-X-Dh4FqOlv7S9b0VkNK_w2GOG4jQ5iqBtoZ34umWvhUWiJXRS9SfB-vVE_zI/33muervatr8acwq/app-release.apk
screenshots:
  - IMG_20240106_093454.jpg
  - IMG_20240106_093547.jpg
  - IMG_20240106_100518.jpg
producthunt: https://www.producthunt.com/posts/capturehealth
companies:
  - url: https://www.producthunt.com/posts/capturehealth
    image: producthunt.png
